# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: psql
    ports:
     - 5432:5432
    volumes: 
     - ./psql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: new_db

  node:
     build: ./node
     restart: always
     container_name: node_app


  web:
     image: nginx:latest
     restart: always
     container_name: nginx
     ports:
       - 80:80
     links:
       - node
     volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf

